# Generated by Django 3.0.9 on 2021-04-21 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Home', 'Home'), ('School', 'School'), ('Work', 'Work'), ('Self Imporvement', 'Self Improvement'), ('Other', 'Other')], max_length=128)),
                ('completed', models.BooleanField(default=False)),
                ('switcharoo', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
