# Generated by Django 3.0.9 on 2021-05-02 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('-------', '-------'), ('Cardio', 'Cardio'), ('Cross-fit', 'Cross-fit'), ('Free Weights', 'Free Weights'), ('Lower-Body', 'Lower-Body'), ('Upper-Body', 'Upper-Body'), ('Yoga', 'Yoga'), ('Other', 'Other')], max_length=128)),
                ('projected', models.DecimalField(decimal_places=1, max_digits=99)),
                ('actual', models.DecimalField(decimal_places=1, max_digits=99)),
                ('res', models.DecimalField(decimal_places=1, default=0.0, max_digits=99)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
